version: '3.3'
services:
  app:
    build:
      context: ./
    depends_on:
      - db-ish
    restart: always
    environment:
      discordToken: ${discordToken}
      token_uptime: ${token_uptime}
      DBhost: db-ish
      DBdatabase: ish
      DBusername: ish
      DBpassword: ${DBpassword}
      DBdialect: mysql
  db-ish:
    image: mariadb:latest
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password_root}
      MYSQL_DATABASE: ish
      MYSQL_USER: ish
      MYSQL_PASSWORD: ${DBpassword}

volumes:
  db_data: