version: '3.3'
services:
  app:
    build:
      context: ./
    depends_on:
      - db-ish
    restart: always
    environment:
      discordToken: ${discordToken}
      token_uptime: ${token_uptime}
      DBhost: db-ish
      DBdatabase: ish
      DBusername: ish
      DBpassword: ${DBpassword}
      DBdialect: mysql
      sentryLink: ${SENTRY_LINK}
  db-ish:
    image: mariadb:latest
    command: --max_allowed_packet=256M
    restart: always
    ports:
      - "${DB_IP}:${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password_root}
      MYSQL_DATABASE: ish
      MYSQL_USER: ish
      MYSQL_PASSWORD: ${DBpassword}
    networks:
      - default
      - grafana_exposed

networks:
  grafana_exposed:
    external: true

volumes:
  db_data:
