name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: stardrive

    env:
      discordToken: ${{ secrets.TOKEN_DISCORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DBpassword: ${{ secrets.DB_PASSWORD }}
      db_password_root: ${{ secrets.DB_PASSWORD_ROOT }}
      token_uptime: ${{ secrets.TOKEN_UPTIME }}

    steps:
      - uses: actions/checkout@v2

      - name: Update 3rd party docker containers
        run: docker compose pull

      - name: Build app
        run: docker compose build

      - name: Spin up containers
        run: docker compose up -d db-ish
